### ISSUE TITLE
workload.py

### ISSUE THREAD

**Issue by nldyy** [fuvty/DeSCo#3]
When I run main.py and get to line 301 in workload.py, an error occurs, but I haven't changed any other code. I'd like to ask for some directions on how to resolve this issue?
![Uploading 屏幕截图 2024-09-13 192601.png…]()

**Comment by fuvty** [comment]
Hi @nldyy , thank you for your question. But it seems that your screenshot was not uploaded correctly. Could you try uploading it again so that we can get a better understanding of what happened?

**Comment by nldyy** [comment]
![1](https://github.com/user-attachments/assets/d14d7c02-6cdd-442e-a122-8634c1a6a688)

**Comment by nldyy** [comment]
I apologize for the initial failed upload. The first image contains the code that caused the error, and the second image shows the error report. Thank you for your response.
![1](https://github.com/user-attachments/assets/7812beed-c5bd-4f14-a436-e43b8b544ce8)
![2](https://github.com/user-attachments/assets/1dca0c73-31cb-4d7b-9d6d-bc5dcb3d0755)

**Comment by fuvty** [comment]
It seems to be a problem related to the in-memory-dataset class of PyG. Which PyG version do you use? Could you try to print all attributes of `self` so that we can better identify the problem?

> I apologize for the initial failed upload. The first image contains the code that caused the error, and the second image shows the error report. Thank you for your response. ![1](https://private-user-images.githubusercontent.com/38241803/369337713-7812beed-c5bd-4f14-a436-e43b8b544ce8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjQ5NTAsIm5iZiI6MTcyNjgyNDY1MCwicGF0aCI6Ii8zODI0MTgwMy8zNjkzMzc3MTMtNzgxMmJlZWQtYzViZC00ZjE0LWE0MzYtZTQzYjhiNTQ0Y2U4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5MzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZjYwNjZlYTRmOGRlMWVhMmU3MWI4ZjE2NGY5Mjg1N2FkNDkyMzM2YzZlYzU3NWE5NDAzZmMxYmE1YzdhYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O5cc5K8fstvtENyvKdDnNPjR9noI5FUgSIayakzQLhk) ![2](https://private-user-images.githubusercontent.com/38241803/369337743-1dca0c73-31cb-4d7b-9d6d-bc5dcb3d0755.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjQ5NTAsIm5iZiI6MTcyNjgyNDY1MCwicGF0aCI6Ii8zODI0MTgwMy8zNjkzMzc3NDMtMWRjYTBjNzMtMzFjYi00ZDdiLTlkNmQtYmM1ZGNiM2QwNzU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5MzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NTk1ZjU0ZjQ5NDQ5YzFkM2E5MGQ1Y2JmZDcwOGM3MTQ5MTlkMWNkYjkwOTU1YTg5NTgwZTg1OTc4MmJkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2MiRQRlbx8wEMmm20DgQ5QJSndLz5iupUFEe4--wZSY)

**Comment by nldyy** [comment]
Here's the version I print：print(torch_geometric.__version__)-------2.5.3
Here are the attributes I understand; not sure if my comprehension is correct.
This is the MUTAG/NeighborhoodDataset/processed/neighs_pyg_depth_4.pt
DeSCo/data/MUTAG/NeighborhoodDataset/processed/neighs_pyg_depth_4.pt'
>>> data = torch.load(file_path)
>>> print(data)
(HeteroData(
  y=[3183, 1],
  count={
    node_feature=[19944, 1],
    count_0=[19944, 1],
    count_-1=[19944, 1],
    count_-2=[19944, 1],
    count_-3=[19944, 1],
    count_-4=[19944, 1],
    count_-5=[19944, 1],
    count_-6=[19944, 1],
    count_-7=[19944, 1],
    count_-8=[19944, 1],
    count_-9=[19944, 1],
    count_-10=[19944, 1],
    count_-11=[19944, 1],
    count_-12=[19944, 1],
    count_-13=[19944, 1],
    count_-14=[19944, 1],
    count_-15=[19944, 1],
    count_-16=[19944, 1],
    count_-17=[19944, 1],
    count_-18=[19944, 1],
    count_-19=[19944, 1],
    count_-20=[19944, 1],
    count_-21=[19944, 1],
    count_-22=[19944, 1],
    count_-23=[19944, 1],
    count_-24=[19944, 1],
    count_-25=[19944, 1],
    count_-26=[19944, 1],
    count_-27=[19944, 1],
    count_-28=[19944, 1],
  },
  canonical={
    node_feature=[3183, 1],
    count_0=[3183, 1],
    count_-1=[3183, 1],
    count_-2=[3183, 1],
    count_-3=[3183, 1],
    count_-4=[3183, 1],
    count_-5=[3183, 1],
    count_-6=[3183, 1],
    count_-7=[3183, 1],
    count_-8=[3183, 1],
    count_-9=[3183, 1],
    count_-10=[3183, 1],
    count_-11=[3183, 1],
    count_-12=[3183, 1],
    count_-13=[3183, 1],
    count_-14=[3183, 1],
    count_-15=[3183, 1],
    count_-16=[3183, 1],
    count_-17=[3183, 1],
    count_-18=[3183, 1],
    count_-19=[3183, 1],
    count_-20=[3183, 1],
    count_-21=[3183, 1],
    count_-22=[3183, 1],
    count_-23=[3183, 1],
    count_-24=[3183, 1],
    count_-25=[3183, 1],
    count_-26=[3183, 1],
    count_-27=[3183, 1],
    count_-28=[3183, 1],
  },
  (count, union, canonical)={ edge_index=[2, 3721] },
  (canonical, union, count)={ edge_index=[2, 3721] },
  (count, union, count)={ edge_index=[2, 35650] }
), {'y': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count': {'node_feature': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_0': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-1': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-2': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-3': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-4': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-5': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-6': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-7': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-8': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-9': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-10': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-11': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-12': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-13': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-14': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-15': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-16': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-17': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-18': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-19': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-20': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-21': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-22': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-23': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-24': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-25': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-26': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-27': tensor([    0,     1,     3,  ..., 19931, 19937, 19944]), 'count_-28': tensor([    0,     1,     3,  ..., 19931, 19937, 19944])}, 'canonical': {'node_feature': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_0': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-1': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-2': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-3': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-4': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-5': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-6': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-7': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-8': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-9': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-10': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-11': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-12': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-13': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-14': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-15': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-16': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-17': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-18': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-19': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-20': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-21': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-22': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-23': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-24': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-25': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-26': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-27': tensor([   0,    1,    2,  ..., 3181, 3182, 3183]), 'count_-28': tensor([   0,    1,    2,  ..., 3181, 3182, 3183])}, ('count', 'union', 'canonical'): {'edge_index': tensor([   0,    1,    2,  ..., 3719, 3720, 3721])}, ('canonical', 'union', 'count'): {'edge_index': tensor([   0,    1,    2,  ..., 3719, 3720, 3721])}, ('count', 'union', 'count'): {'edge_index': tensor([    0,     0,     2,  ..., 35628, 35638, 35650])}})

**Comment by nldyy** [comment]
data/MUTAG/NeighborhoodDataset/processed/neighs_indicator_depth_4.npy：
[False  True  True ...  True  True  True]

MUTAG/NeighborhoodDataset/processed/neighs_index_depth_4.npy：
[[  0   1]
 [  0   2]
 [  0   3]
 ...
 [187  13]
 [187  14]
 [187  15]]

data/MUTAG/NeighborhoodDataset/processed/pre_filter.pt：
None

MUTAG/NeighborhoodDataset/processed/pre_transform.pt：
None

**Comment by nldyy** [comment]
I printed out the files in the MUTAG/NeighborhoodDataset/processed directory, and indeed, I did not see the 'data' attribute when I checked before.Thank you for your response.

**Comment by fuvty** [comment]
The data.y should be the label for prediction. If the data attribute does not exist, could you try to simply add that attribute before assigning the value?

**Comment by nldyy** [comment]
I've noticed a peculiar situation where in the “process()” function of the “workload.py” file, executing the line “data, slices = self.collate(neighs_pyg)” and then printing “data” and “slices” does not raise any errors. However, within the “NeighborhoodDataset” class in “workload.py”, after executing “self.data, self.slices = torch.load(self.processed_paths[0])”, printing “data” results in an error, while “slices” remains consistent.

**Comment by nldyy** [comment]
I've made an interesting discovery while modifying the code in the “NeighborhoodDataset” class of “workload.py”. The first print statement for “data” outputs normally, but the second one, when accessing “self.data”, results in an error: "In 'site-packages/torch_geometric/data/in_memory_dataset.py', line 319, in `__getattr__`, an AttributeError is raised stating that the 'NeighborhoodDataset' object has no attribute 'data'."
![3](https://github.com/user-attachments/assets/ab9b2aeb-83d8-41c6-b118-13c94ba32ccc)

**Comment by nldyy** [comment]
I resolved the issue by setting up the environment again. Thank you for your response and assistance.
