### ISSUE TITLE
About the reproduction of results

### ISSUE THREAD

**Issue by nldyy** [fuvty/DeSCo#4]
When reproducing the experimental results using the provided checkpoint files on datasets such as MUTAG, COX2, ENZYMES, IMDB-BINARY, MSRC-21, Citeseer, and Cora, I found that the results were largely consistent with those in the paper for all except IMDB-BINARY and Citeseer. The experimental outcomes for these two datasets, however, showed significant discrepancies. I'm wondering if anyone has encountered a similar situation and what might be the probable causes?

**Comment by fuvty** [comment]
Could you provide additional experimental details to help us diagnose the issue? Based on the datasets you mentioned, one possible cause might be how the nodes are indexed. Are they indexed randomly, or by descending degree?

You can refer to [this link](https://github.com/fuvty/DeSCo/blob/4508f7a99fd9eceb18e04f0b6344df9105a47f7e/subgraph_counting/data.py#L120) for guidance on re-indexing nodes with our codebase, ensuring that nodes with high degrees have lower indices. This adjustment could help control the size of their canonical neighborhoods.

**Comment by nldyy** [comment]
Thank you for your reply. I previously tested directly using the downloaded dataset. I have now completed the testing on the IMDB-BINARY dataset using descending order indexing, and the experimental results are consistent with those in the paper!

**Comment by fuvty** [comment]
Thank you for the follow-up. Welcome to star the repo if you are interested :)
